### ISSUE TITLE
Can't login via REST

### ISSUE THREAD

**Issue by Grizzgore** [AnAlgoTrader/IG.Csharp.Api.Client#1]
Hi,

I'm lightly confused, the personalSettings.json doesn't exist, so it coulnt connect via the samplemethods. I created anjson, but it doesnt work ether? Maybe you can give me a hint. But, anyway, good Job done so far.

Cheers ✌️

**Comment by AnAlgoTrader** [comment]
Hi, I have added a README file where I set a few notes on the settings file.

https://github.com/AnAlgoTrader/IG.Csharp.Api.Client/blob/master/README.md

**Comment by Grizzgore** [comment]
Good Job Sir, good Job! Works perfect. Btw, is there any Chance you will include lightstreamer to this? Asking for a Friend. 😉

Cheers. ✌️

**Comment by AnAlgoTrader** [comment]
The streaming client is in the other folder.

https://github.com/AnAlgoTrader/IG.Csharp.Api.Client/tree/master/IG.Csharp.Api.Client/Streaming

Let me know if you need an example.
