### ISSUE TITLE
MidOpen has no value when streaming epic CS.D.BITCOIN.TODAY.IP

### ISSUE THREAD

**Issue by Slashernator** [AnAlgoTrader/IG.Csharp.Api.Client#5]
Hi,

I've just run the streamer and noticed that the MidOpen is null when running against the above epic.  I've checked the lightstreamer companion and this does have a value.  Plus a few others in the attached screenshot.
![Capture](https://user-images.githubusercontent.com/72745405/157198991-73a457ef-fba5-4ccb-bd08-99a6438a6206.PNG)

I also noticed that the null value fields have an underscore in them.  I altered this in the marketdata.cs and the data now appears.  Attached is the streaming companion field def.  Hope this helps?
![Capture2](https://user-images.githubusercontent.com/72745405/157201328-ce9a7da2-9ec5-4aa2-a7da-bf3daa4f26d1.PNG)

**Comment by AnAlgoTrader** [comment]
Hi, some attributes had an underscore in the attribute name and they weren't handled in code. I've sent an update.
Please get the latest and let me know.

**Comment by Slashernator** [comment]
Sorry, forgot to say thanks for doing that, much appreciated :-)

**Comment by AnAlgoTrader** [comment]
no problem buddy, thanks for the message.
